baseURL: "https://mafyuh.github.io/"
title: "Mafyuh's Blog"
theme: "PaperMod"

params:
  env: production
  title: "Mafyuh's Blog"
  description: "A blog by Mafyuh"
  keywords: ["Blog", "Portfolio", "PaperMod"]
  author: "Mafyuh"
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false
  socialIcons:
    - name: reddit
      url: "https://reddit.com/user/Mafyuh"
    - name: gitea
      url: "https://git.mafyuh.dev"
    - name: github
      url: "https://github.com/Mafyuh"
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10
    keys: ["title", "permalink", "summary", "content"]
  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/assets/favicon/favicon.svg"
    favicon16x16: "/assets/img/newlogo.png"
    favicon32x32: "/assets/img/newlogo.png"
    # apple_touch_icon: "<link / abs url>"
    # safari_pinned_tab: "<link / abs url>"
  label:
    text: "Mafyuh's Blog"
    icon: /assets/favicon/favicon.svg
    iconHeight: 35
  profileMode:
    enabled: true # needs to be explicitly set
    title: Mafyuh
    subtitle: "Selfhoster"
    imageUrl: "/assets/favicon/favicon.svg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

menu:
  main:
    - identifier: categories
      name: Guides
      url: /guides/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20

markup:
  highlight:
    noClasses: false

